/* CS261- Assignment 1 - Q.4*/
/* Name: Eli Goodwin
 * Date: 2017.01.18
 * Solution description: a struct array is dynamically allocated and filled with random IDs and scores. The struct array is then sorted by ascending score.
 */
 
#include <stdio.h>
#include<stdlib.h>
#include<math.h>

struct student{
	int id;
	int score;
};

/*sort function for sorting student scores */
void sort(struct student* students, int n){
     /*Sort the n students based on their score*/
    /*sort is implemented using a bubble sort*/

    int tempID; //stores id temporarily
    int tempScore; //stores score temporarily
    
    for(int i = 0; i < n - 1; ++i){
        for(int j = 0; j < n - i - 1; ++j){
            if(students[j].score > students[j + 1].score){
                tempID = students[j].id;
                tempScore = students[j].score;
                students[j].id = students[j + 1].id;
                students[j].score = students[j + 1].score;
                students[j + 1].id = tempID;
                students[j + 1].score = tempScore;
            }
        }
    }
    
    return;
}


int main(){
    /*Declare an integer n and assign it a value.*/
    int n = 10; //number of students
    int randomID = 0; //ID generated by random
    int randomScore = 0; //Score generated by random
    int foundScore  = 0; //flag for score
    int foundID = 0;    //flag for id
    int uniqueID = 0; //flag for unique id
    int uniqueScore = 0; //flag for unique score
    int count = 0; //count for while loops
    
    /*Allocate memory for n students using malloc.*/
    struct student* students = malloc(n * sizeof(struct student));
    /*Generate random and unique IDs and random scores for the n students, using rand().*/
    srand(time(NULL));
    

    for(int i = 0; i < n; ++i){
        //keep generating IDs until one is made that is not used
        while(uniqueID == 0){
            randomID = rand() % n + 1;
            //test if the randomID is in the struct array
            while(count < n && foundID == 0){
                if(randomID == students[count].id){
                    foundID = 1;
                }
                ++count;
            }
            
            //was the id unique? if yes, store it
            if(foundID == 0){
                uniqueID = 1;
                students[i].id = randomID;
            }
            
            count = 0; //reset count
            foundID = 0; //reset found flag
        }
        uniqueID = 0;
        
        //keep generating scores until one is made that is not used
        while(uniqueScore == 0){
            randomScore = rand() % 101;
            //test if the randomScore is in the struct array
            while(count < n && foundScore == 0){
                if(randomScore == students[count].score){
                    foundScore = 1;
                }
                ++count;
            }
            
            //was the score unique? if yes store it
            if(foundScore == 0){
                uniqueScore = 1;
                students[i].score = randomScore;
            }
            
            count = 0; //reset count
            foundScore = 0; //reset found flag
        }
        
        uniqueScore = 0;
        
    }
    
    
    
    
    /*Print the contents of the array of n students.*/
    printf("\nUnsorted Student list (ID Score)\n");
    for(int i = 0; i < n; ++i){
        printf("\n%i %i", students[i].id, students[i].score);
    }
    
    printf("\n");
    
    /*Pass this array along with n to the sort() function*/
    sort(students, n);
    
    printf("\nSorted Student list (ID Score)\n");
    
    /*Print the contents of the array of n students.*/
    for(int i = 0; i < n; ++i){
        printf("\n%i %i", students[i].id, students[i].score);
    }
    
    printf("\n");
    
    return 0;
}
